version: "3.7"
x-app-container:
  &app-container
  build: .
  env_file:
    - ./configurations/.env
  volumes:
    - .:/usr/src/app
  depends_on:
    - mongo

services:
  app:
    << : *app-container
    ports:
     - "8000:80"
  mongo:
    image: mongo
    env_file:
      - ./configurations/.env
      
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db

networks:
  default:
    driver: bridge
